innovation/urls.py
from django.urls import include, path
from django.conf import settings
from stories.views import classroom, students, teachers
from django.contrib import admin
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.utils.translation import ugettext


urlpatterns = [
    
 
   
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += i18n_patterns( # < here
    path('', include('stories.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', classroom.SignUpView.as_view(), name ='signup'),
    path('accounts/signup/student/', students.StudentSignUpView.as_view(), name ='student_signup'),
    path('accounts/signup/teacher/', teachers.TeacherSignUpView.as_view(), name='teacher_signup'),
    path('djrichtextfield/', include('djrichtextfield.urls')),
    
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stories/urls.py
from django.urls import include, path
from .views import classroom, students, teachers



urlpatterns = [
    path('', classroom.home, name='home'),
    path('Innovtion/', classroom.Introduction, name='Introduction'),
    path('Stories/', classroom.Stories, name='Stories'),
    path('Research/', classroom.Research, name='Research'),
    path('teachers/', include(([
        path('', teachers.TeachersListView.as_view(), name='stories_list'),
        path('studies/tables/', teachers.TableListView.as_view(), name='table_list'),
        path('comments/<int:pk>/', teachers.EvaluerlistView, name='comment_list'),
        path('case/<int:pk>/', teachers.take_quiz, name='take_quiz'),
         path('case/Remove/<int:pk>/', teachers.DeleteView, name='delete_quiz'),
        path('story/<int:pk>/', teachers.publi_quiz, name='publi_quiz'),
        path('studies/', teachers.modifaction, name='modif_quiz'),
         path('board/dates/', teachers.DatesListView.as_view(), name='dates_list'),
        

        
#<int:pk>/

    ], 'stories'), namespace='teachers')),

   path('students/', include(([    
        path('', students.HomeListView.as_view(), name='students_home'),
        path('board/', students.StudiesListView.as_view(), name='students_borad'),
        path('board/tables/', students.TableListView.as_view(), name='table_list'),
        path('board/dates/', students.DatesListView.as_view(), name='dates_list'),
        path('case/add/', students.CaseCreateView.as_view(), name='case_add'),
        path('case/<int:pk>/change', students.CaseUpdateView.as_view(), name='case_change'),
        path('case/<int:pk>/delete/', students.QuizDeleteView.as_view(), name='case_delete'),
        path('case/<int:pk>/display', students.post_detail, name='post_detail'),
        path('case/<int:pk>/evaluation', students.evaluation_quiz, name='evalu_detail'),
        ], 'stories'), namespace='students')),

]

stories/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from django.forms.utils import ValidationError
from stories.models import (Cases, School, Student, User, Teacher, Comment, Storie)
from django.forms import ModelChoiceField
from django.forms import ModelMultipleChoiceField
from django.forms import ModelForm
from django.utils.translation import ugettext



class TeacherSignUpForm(UserCreationForm):
    
    
    Schools = forms.ModelMultipleChoiceField(
        queryset=School.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )
   
 
    class Meta(UserCreationForm.Meta):
        model = User
      
    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_teacher = True
        user.save()
        teacher = Teacher.objects.create(user=user)
        teacher.school.add(*self.cleaned_data.get('Schools'))
        return user


class StudentSignUpForm(UserCreationForm):
    Schools = forms.ModelMultipleChoiceField(
        queryset=School.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )

    class Meta(UserCreationForm.Meta):
        model = User

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_student = True
        user.save()
        student = Student.objects.create(user=user)
        student.school.add(*self.cleaned_data.get('Schools'))
        return user


class GroupForm(ModelForm):
    class Meta:
       model = Cases
       fields = ['title_case', 'subject', 'produit', 'context', 'description', 'description_shema', 'processus']



class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('title_comment', 'state_comment', 'produit_comment', 'context_comment', 'description_comment', 'diagnostic_comment', 'processus_comment', 'references_comment', 'abstract_comment',  'general_remarks'   )


class StorieForm(forms.ModelForm):

    class Meta:
        model = Storie
        fields = ['story']
      

stories/views/classroom.py
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from django.utils import timezone
from django.utils.translation import ugettext
from ..models import Cases, Student, User, School
from  stories.filters import CasesFilter


class SignUpView(TemplateView):
    template_name = 'registration/signup.html'


def home(request):
    if request.user.is_authenticated:
        if request.user.is_teacher:
            return redirect('teachers:stories_list')
        else:
            return redirect('students:students_borad')
    return render(request, 'classroom/home.html')


    
def Introduction(request):
     template_name = 'classroom/Introduction.html'
     return render(request, template_name)



def Research(request):
     case_list = Cases.objects.all()
     case_filter = CasesFilter(request.GET, queryset = case_list)
     template_name = 'classroom/research.html'
     return render(request, template_name, {'filter' : case_filter})



def Stories(request):
     posts = Cases.objects.filter(created_date__lte=timezone.now()).order_by('created_date')
     return render(request, 'classroom/stories.html', {'posts':posts})

stories/views/students.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Count
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from ..decorators import student_required
from ..forms import  StudentSignUpForm, GroupForm
from ..models import Cases, Student, User, School, Comment, SummaryHistory
from django.utils.translation import ugettext
from django.utils import timezone
from django.http import HttpResponseRedirect
from django.http import Http404



class StudentSignUpView(CreateView):
    model = User
    form_class = StudentSignUpForm
    template_name = 'registration/signup_form_student.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'student'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('students:students_borad')



class HomeListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/students/index.html'

@method_decorator([login_required, student_required], name='dispatch')
class StudiesListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/students/board/index.html'



@method_decorator([login_required, student_required], name='dispatch')
class TableListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/students/board/tables-basic.html'

    def get_queryset(self):
        queryset = self.request.user.cases \
            .select_related('school_case') 
        return queryset


@method_decorator([login_required, student_required], name='dispatch')
class DatesListView(ListView):
    model = School
    context_object_name = 'cases'
    template_name ='classroom/students/board/dates.html'
    
    def get_queryset(self):
        queryset = self.request.user.student.school\
            .prefetch_related('students_school') 
        return queryset






@method_decorator([login_required, student_required], name='dispatch')
class CaseCreateView(CreateView):
    model = Cases
    fields = ('title_case', 'subject',  'produit', 'mois', 'image_produit', 'date', 'context', 'context_images', 'description', 'description_shema',  'diagnostic',  'diagnostic_shema',  'processus',  'processus_shema',  'reference', 'abstract', 'auteur', 'school_case', 'terms_and_conditions')
    template_name = 'classroom/students/board/forms-basic.html'
    #case_add_form

    def form_valid(self, form):
        case = form.save(commit=False)
        case.owner = self.request.user
        case.save()
        return redirect('students:case_change', case.pk)


@method_decorator([login_required, student_required], name='dispatch')
class CaseUpdateView(UpdateView):
    model = Cases
    fields = fields = ('title_case', 'subject', 'produit', 'mois', 'image_produit', 'date', 'context', 'context_images', 'description', 'description_shema',  'diagnostic',  'diagnostic_shema',  'processus',  'processus_shema',  'reference', 'abstract', 'auteur', 'school_case', 'terms_and_conditions')
    context_object_name = 'case'
    template_name = 'classroom/students/case_change_form.html'
    
    def get_queryset(self):
        '''
        This method is an implicit object-level permission management
        This view will only match the ids of existing quizzes that belongs
        to the logged in user.
        '''
        return self.request.user.cases.all()
 
    def form_valid(self, form):
        case = form.save(commit=False)
        case.update_date = timezone.now()
        case.save()
        return redirect('students:case_change', case.pk)


        



@method_decorator([login_required, student_required], name='dispatch')
class QuizDeleteView(DeleteView):
    model = Cases
    context_object_name = 'case'
    template_name = 'classroom/students/case_delete_confirm.html'
    success_url = reverse_lazy('students:table_list')

    def delete(self, request, *args, **kwargs):
        quiz = self.get_object()
        messages.success(request, 'The quiz %s was deleted with success!' % quiz.title_case)
        return super().delete(request, *args, **kwargs)

    def get_queryset(self):
        return self.request.user.cases.all()







def post_detail(request, pk):
    post = get_object_or_404(Cases, pk=pk)
    return render(request, 'classroom/home/landing.html', {'post': post})
    
    #return render(request, 'classroom/students/case_form_display.html', {'post': post})
    


@login_required
@student_required
def evaluation_quiz(request, pk):
    try:
        quiz = get_object_or_404(Cases, pk=pk)
        Comments = Comment.objects.filter(case__pk= quiz.pk).order_by('date_comment')
    except Comment.DoesNotExist:
            raise Http404('cases does not exist')

    return render(request, 'classroom/students/board/evaluation_resultat.html', {'Comments': Comments}  )

stories/views/teachers.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Avg, Count
from django.forms import inlineformset_factory
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse, reverse_lazy
from django.utils.decorators import method_decorator
from ..decorators import teacher_required
from ..models import Cases, Teacher, School, User,  Comment, SummaryHistory
from django.views.generic import CreateView, ListView, UpdateView
from ..forms import  TeacherSignUpForm, CommentForm, StorieForm
from django.http import HttpResponse
from django.template import loader
from django.http import Http404
from django.utils.translation import ugettext
from django.shortcuts import render
from django.http import HttpResponseRedirect



class TeacherSignUpView(CreateView):
    model = User
    form_class = TeacherSignUpForm
    template_name = 'registration/signup_form_teacher.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'teacher'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect('teachers:stories_list')



@method_decorator([login_required, teacher_required], name='dispatch')
class TeachersListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/teachers/board/index.html'


@method_decorator([login_required, teacher_required], name='dispatch')
class TableListView(ListView):
    model = Cases
    ordering = ('title_case', )
    context_object_name = 'cases'
    template_name = 'classroom/teachers/board/tables-basic.html'

    def get_queryset(self):
        teacher = self.request.user.teacher
        teacher_schools = teacher.school.values_list('pk', flat=True)
        # taken_quizzes = student.quizzes.values_list('pk', flat=True)
        queryset = Cases.objects.filter(school_case__in = teacher_schools) 
        return queryset



def EvaluerlistView(request, pk):
    try:
        comment = get_object_or_404(Comment, pk=pk)
    except Comment.DoesNotExist:
            raise Http404('cases does not exist')

    return render(request, 'classroom/teachers/board/takens.html', {'comment': comment}  )


@login_required
@teacher_required
def take_quiz(request, pk):
    quiz = get_object_or_404(Cases, pk=pk)
    teacher = request.user.teacher
    template_name = 'registration/signup_form_teacher.html'

    try:

        summary_history = SummaryHistory.objects.filter(case__pk= quiz.pk).order_by('-version')
    except summary_history.DoesNotExist:
            raise Http404('cases does not exist')

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.case= quiz
            post.owner = request.user
            post.save()
            return redirect('teachers:take_quiz', quiz.pk)
    else:

        form = CommentForm()
        try:
            quiz = get_object_or_404(Cases, pk=pk)
            Comments = Comment.objects.filter(case__pk= quiz.pk).order_by('date_comment')
        except Comment.DoesNotExist:
               raise Http404('cases does not exist')

    return render(request, 'classroom/teachers/board/forms.html', {'form': form, 'quiz':quiz, 'Comments': Comments, 'summary_history': summary_history})




@login_required
@teacher_required
def modifaction(request, pk):
    try:
        quiz = get_object_or_404(Cases, pk=pk)
        summary_history = SummaryHistory.objects.filter(case__pk= quiz.pk).order_by('-version')
    except summary_history.DoesNotExist:
            raise Http404('cases does not exist')

    return render(request, 'classroom/teachers/board/tables-basic.html', {'summary_history': summary_history}  )




@method_decorator([login_required, teacher_required], name='dispatch')
class DatesListView(ListView):
    model = School
    context_object_name = 'cases'
    template_name ='classroom/teachers/board/dates.html'
    
    def get_queryset(self):
        queryset = self.request.user.teacher.school\
            .prefetch_related('teacher_school') 
        return queryset



@login_required
@teacher_required
def DeleteView(request, pk):
    try:
           quiz = get_object_or_404(Cases, pk=pk).delete()
    except quiz.DoesNotExist:
            raise Http404('cases does not exist')

    return render(request, 'classroom/teachers/board/tables-basic.html' )










@login_required
@teacher_required
def publi_quiz(request, pk):
    quiz = get_object_or_404(Cases, pk=pk)
  

    if request.method == "POST":
        form = StorieForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.case= quiz
            post.save()
            return redirect('teachers:take_quiz', quiz.pk)
    else:
        raise Http404(' ')




  







    

stories/templates/classroom/recherche.html
{% extends 'base.html' %}

{% block content %}
  <form method="get">
    {{ filter.form.as_p }}
    <button type="submit">Search</button>
  </form>
  <ul>
  {% for user in filter.qs %}
    <li>{{ user.name }} - {{ user.abstract }}</li>
  {% endfor %}
  </ul>
{% endblock %}

stories/templates/classroom/research.html
{%load static%}
{% load i18n %}
    
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="author" content="Colorlib">
    <meta name="description" content="#">
    <meta name="keywords" content="#">
    <!-- Page Title -->
    <title>Stories research</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'Introduction/home/css/bootstrap.min.css' %}">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,400i,500,700,900" rel="stylesheet">
    <!-- Simple line Icon -->
    <link rel="stylesheet" href="{% static 'Introduction/home/css/simple-line-icons.css' %}">
    <!-- Themify Icon -->
    <link rel="stylesheet" href="{% static 'Introduction/home/css/themify-icons.css' %}">
    <!-- Hover Effects -->
    <link rel="stylesheet" href="{% static 'Introduction/home/css/set1.css' %}">
    <!-- Main CSS -->
    <link rel="stylesheet" href="{% static 'Introduction/home/css/style.css' %}">
</head>

<body>
    <!--============================= HEADER =============================-->
    <div class="nav-menu">
        <div class="bg transition">
            <div class="container-fluid fixed">
                <div class="row">
                    <div class="col-md-12">
                        <nav class="navbar navbar-expand-lg navbar-light">
                                <header id="header" class="alt">
                                        <a href="{% url 'Introduction' %}" class="logo"><strong>Innovation</strong><span style="color: aliceblue;">Stories</span></a>
                                </header>
                            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                <span class="icon-menu"></span>
              </button>
                            <div class="collapse navbar-collapse justify-content-end" >
                                <ul class="navbar-nav">
                                    
                                    <li><a href="{% url 'Introduction' %}" class="btn btn-outline-light top-btn"><span class="ti-plus"></span>Come join us</a></li>
                                </ul>
                            </div>
                        </nav>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- SLIDER -->
    <section class="slider d-flex align-items-center">
        <!-- <img src="{% static 'Introduction/home/images/slider.jpg" class="img-fluid" alt="#"> -->
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-12">
                    <div class="slider-title_box">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="slider-content_wrap">
                                    <h1>Discover the best innovative stories in The World </h1>
                                    <h5>Let's uncover the best stories, you can search by Case Study, Process, Subject...</h5>
                                </div>
                            </div>
                        </div>
                        <div class="row d-flex justify-content-center">
                            <div class="col-md-10">

                                    {% load widget_tweaks %}
                              
                                    <form method="get">
                                            <div class="well">
                                            <div class="well">
                                             
                                              <div class="row">
                                                <div class="form-group col-sm-4 col-md-3">
                                                        <h6 style="margin-top: 0; color: aliceblue;">Story</h6>
                                                  {% render_field filter.form.title_case class="form-control" %}
                                                  <h4 style="margin-top: 0"></h4>
                                                </div>
                                                <div class="form-group col-sm-4 col-md-3">
                                                        <h6 style="margin-top: 0; color: aliceblue;">Process</h6>
                                                  {% render_field filter.form.processus class="form-control" %}
                                                  <h4 style="margin-top: 0"></h4>
                                                </div>
                                                <div class="form-group col-sm-4 col-md-3">
                                                        <h6 style="margin-top: 0; color: aliceblue;">Subject</h6>
                                                  {% render_field filter.form.subject class="form-control" %}
                                                  <h4 style="margin-top: 0"></h4>
                                                </div>
                                                <div class="form-group col-sm-4 col-md-3">
                                                        <h6 style="margin-top: 0; color: aliceblue;">Month</h6>
                                                        {% render_field filter.form.mois class="form-control" %}
                                                        <h4 style="margin-top: 0"></h4>
                                                        <h4 style="margin-top: 0"></h4>
                                                      </div>
                                            </div>
                                                        
                                            <button type="submit" class="btn-form"><span class="icon-magnifier search-icon"></span>SEARCH<i class="pe-7s-angle-right"></i></button>   
                                                
                                                            </div>
                                              
                                          </form>

                                          <div class="row">
                                                <div class="form-group col-sm-4 col-md-3">
                                                  <h6 style="margin-top: 0; color: aliceblue;"></h6>
                                                  <h4 style="margin-top: 0"></h4>
                                                  <h6 style="margin-top: 0; color: aliceblue;"></h6>
                                                  <h4 style="margin-top: 0"></h4>
                                                  <h6 style="margin-top: 0; color: aliceblue;"></h6>
                                                  <h4 style="margin-top: 0"></h4>
                                                </div>
                                                
                                            </div>
                                 



                                <div class="slider-link">
                                    <a href="#">Browse Popular</a><span>or</span> <a href="{% url 'Stories' %}">Recently Added</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--// SLIDER -->
    <!--//END HEADER -->
    <!--============================= FIND PLACES =============================-->
    <section class="main-block">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-5">
                    <div class="styled-heading">
                        <h3>What do you need to find?</h3>
                    </div>
                </div>
            </div>
            <div class="row">


                          {% for user in filter.qs %}
                    
                            
                                <div class="pricing-box  text-center">
                                        <h5 style=" font-size: 25px;"></h5>
                                        <h5 style=" font-size: 30px;"></h5>
                                    <h5 style=" font-size: 20px;">{{ user.title_case }}</h5>
                                    <p class="price"></p>
                                    <ul class="features-list">
                                        <li><strong></strong> {{ user.produit }}</li>
                                        <li><strong></strong> {{ user.subject  }}</li>
                                        <li><strong></strong> {{ user.school_case }}</li>
                                        <li><strong></strong> {{ user.auteur}}</li>
                                    </ul>
                                    <form action="{% url 'students:post_detail' user.pk %}" method="get" target="_blank">
                                        <button class="btn-primary" type="submit">Get Started</button>
                                    </form>
                                   
                                </div>
                            

                    
                        {% empty %}
  
                        <p class="text-center">  No data are availbe about this Case Study</p>   
                                 
                          


                           {% endfor %}



            
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--//END FIND PLACES -->
    <!--============================= FEATURED PLACES =============================-->
 
    <!--//END FEATURED PLACES -->
    <!--============================= CATEGORIES =============================-->
   
    <!--//END CATEGORIES -->
    <!--============================= ADD LISTING =============================-->
    <section class="main-block light-bg">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="add-listing-wrap">
                        <h2>Reach millions of Stories</h2>
                        <p></p>
                    </div>
                </div>
            </div>
            <div class="row justify-content-center">
                <div class="col-md-4">
                    <div class="featured-btn-wrap">
                        <a href="{% url 'students:students_home' %}" class="btn btn-danger"><span class="ti-plus"></span> ADD STORIES</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--//END ADD LISTING -->
    <!--============================= FOOTER =============================-->
    <footer class="main-block dark-bg">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="copyright">
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        <p>Copyright &copy; ERPI 2019. All rights reserved | This template is designed with <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a></p>
                        <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                        <ul>
                            <li><a href="#"><span class="ti-facebook"></span></a></li>
                            <li><a href="#"><span class="ti-twitter-alt"></span></a></li>
                            <li><a href="#"><span class="ti-instagram"></span></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--//END FOOTER -->




    <!-- jQuery, Bootstrap JS. -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="{% static 'Introduction/home/js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'Introduction/home/js/popper.min.js' %}"></script>
    <script src="{% static 'Intrroduction/home/js/bootstrap.min.js' %}"></script>

    <script>
        $(window).scroll(function() {
            // 100 = The point you would like to fade the nav in.

            if ($(window).scrollTop() > 100) {

                $('.fixed').addClass('is-sticky');

            } else {

                $('.fixed').removeClass('is-sticky');

            };
        });
    </script>
</body>

</html>